version: 2
jobs:
  build:
    docker:
       - image: debian:9.5
    steps:
      - checkout
      - run:
          name: Installing dependencies
          command: ./install_deps_debian.sh
      - run:
          name: Building
          command: ./build_ffmpeg.sh
      - run:
          name: Deploy
          command: ./deploy.sh
workflows:
  version: 2
  commit:
    jobs:
      - build
  nightly:
    triggers:
      - schedule:
          cron: "50 3 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
